CREATE DATABASE IF NOT EXISTS demodb;
USE  demodb;
CREATE TABLE IF NOT EXISTS url_mappings(
    id INT(11) NOT NULL AUTO_INCREMENT,
    short_url VARCHAR(255) NOT NULL,
    long_url VARCHAR(300) NOT NULL,
    PRIMARY KEY(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;